[package]
name = "cargo-tools"
description = "A cargo tool to facilitate building mobile apps with rapp"

version.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "rapp"

[dependencies]
