[package]
name = "rapp_runner"
version = "0.1.0"
rust-version = "1.65"
edition = "2021"

[dependencies]
runner = { path = "../../../../runner" }
rapp = { path = "../../../../rapp" }

# the user's app
app = { path = "${dir}/${name}", package = "${name}" }

[workspace]
